# Generated by Django 2.1.7 on 2019-02-14 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabprosessing',
            name='requestid',
            field=models.PositiveIntegerField(verbose_name=41662),
        ),
    ]
