# Generated by Django 2.1.7 on 2019-02-14 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190214_1739'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requestid', models.PositiveIntegerField()),
                ('Date', models.DateField()),
                ('Time', models.TimeField()),
                ('Servicetype', models.CharField(max_length=250)),
                ('Source', models.CharField(max_length=250)),
                ('Destination', models.CharField(max_length=250)),
                ('Driversname', models.CharField(max_length=250)),
                ('fare', models.PositiveIntegerField()),
                ('ratings', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='cabprosessing',
            name='requestid',
            field=models.PositiveIntegerField(),
        ),
    ]
