# Generated by Django 2.1.7 on 2019-02-14 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190214_1802'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cabprosessing',
            old_name='ststus',
            new_name='status',
        ),
    ]
