# Generated by Django 2.1.7 on 2019-02-15 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190214_1806'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='consumer',
            new_name='Consumer_Db',
        ),
    ]
