# Generated by Django 2.1.7 on 2019-02-15 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190215_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role_per',
            name='perr',
            field=models.TextField(),
        ),
    ]
